/*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    */

//filter array param for even numbers (divisible by 2)
function filter(x)
{
    var arr = x.filter(function(z){
        return z % 2 == 0;
    })
    return arr;
}

//store fibonacci sequence
var seq = [1, 2];

//loop and push for values under 4 million to seq.
while(seq[seq.length - 1] < 4000000)
{
    seq.push(seq[seq.length - 1] + seq[seq.length - 2]);
}

//show sum of seq's even numbers
console.log(filter(seq).reduce((acc, curr) => acc + curr, 0));